### ISSUE TITLE
The decoder keys are incompatible  in your generate case

### ISSUE THREAD

**Issue by holdrain** [facebookresearch/stable_signature#15]

**Comment by holdrain** [comment]
the ckpt i used is sd2_decoder.pth, but all keys of decoder are incompatible when i implement load_state_dict... in your generate script

**Comment by pierrefdz** [comment]
Hi!
Would you be able to share the error message? 
(it could be linked to "In this case, the state dict only contains the 'ldm_decoder' key, so you only need to load with state_dict = torch.load(path/to/ckpt.pth)" - see https://github.com/facebookresearch/stable_signature?tab=readme-ov-file#generate).

**Comment by holdrain** [comment]
_IncompatibleKeys(missing_keys=['encoder.conv_in.weight', 'encoder.conv_in.bias', 'encoder.down_blocks.0.resnets.0.norm1.weight', 'encoder.down_blocks.0.resnets.0.norm1.bias', 'encoder.down_blocks.0.resnets.0.conv1.weight', 'encoder.down_blocks.0.resnets.0.conv1.bias', 'encoder.down_blocks.0.resnets.0.norm2.weight', 'encoder.down_blocks.0.resnets.0.norm2.bias', 'encoder.down_blocks.0.resnets.0.conv2.weight', 'encoder.down_blocks.0.resnets.0.conv2.bias', 'encoder.down_blocks.0.resnets.1.norm1.weight', 'encoder.down_blocks.0.resnets.1.norm1.bias', 'encoder.down_blocks.0.resnets.1.conv1.weight', 'encoder.down_blocks.0.resnets.1.conv1.bias', 'encoder.down_blocks.0.resnets.1.norm2.weight', 'encoder.down_blocks.0.resnets.1.norm2.bias', 'encoder.down_blocks.0.resnets.1.conv2.weight', 'encoder.down_blocks.0.resnets.1.conv2.bias', 'encoder.down_blocks.0.downsamplers.0.conv.weight', 'encoder.down_blocks.0.downsamplers.0.conv.bias', 'encoder.down_blocks.1.resnets.0.norm1.weight', 'encoder.down_blocks.1.resnets.0.norm1.bias', 'encoder.down_blocks.1.resnets.0.conv1.weight', 'encoder.down_blocks.1.resnets.0.conv1.bias', 'encoder.down_blocks.1.resnets.0.norm2.weight', 'encoder.down_blocks.1.resnets.0.norm2.bias', 'encoder.down_blocks.1.resnets.0.conv2.weight', 'encoder.down_blocks.1.resnets.0.conv2.bias', 'encoder.down_blocks.1.resnets.0.conv_shortcut.weight', 'encoder.down_blocks.1.resnets.0.conv_shortcut.bias', 'encoder.down_blocks.1.resnets.1.norm1.weight', 'encoder.down_blocks.1.resnets.1.norm1.bias', 'encoder.down_blocks.1.resnets.1.conv1.weight', 'encoder.down_blocks.1.resnets.1.conv1.bias', 'encoder.down_blocks.1.resnets.1.norm2.weight', 'encoder.down_blocks.1.resnets.1.norm2.bias', 'encoder.down_blocks.1.resnets.1.conv2.weight', 'encoder.down_blocks.1.resnets.1.conv2.bias', 'encoder.down_blocks.1.downsamplers.0.conv.weight', 'encoder.down_blocks.1.downsamplers.0.conv.bias', 'encoder.down_blocks.2.resnets.0.norm1.weight', 'encoder.down_blocks.2.resnets.0.norm1.bias', 'encoder.down_blocks.2.resnets.0.conv1.weight', 'encoder.down_blocks.2.resnets.0.conv1.bias', 'encoder.down_blocks.2.resnets.0.norm2.weight', 'encoder.down_blocks.2.resnets.0.norm2.bias', 'encoder.down_blocks.2.resnets.0.conv2.weight', 'encoder.down_blocks.2.resnets.0.conv2.bias', 'encoder.down_blocks.2.resnets.0.conv_shortcut.weight', 'encoder.down_blocks.2.resnets.0.conv_shortcut.bias', 'encoder.down_blocks.2.resnets.1.norm1.weight', 'encoder.down_blocks.2.resnets.1.norm1.bias', 'encoder.down_blocks.2.resnets.1.conv1.weight', 'encoder.down_blocks.2.resnets.1.conv1.bias', 'encoder.down_blocks.2.resnets.1.norm2.weight', 'encoder.down_blocks.2.resnets.1.norm2.bias', 'encoder.down_blocks.2.resnets.1.conv2.weight', 'encoder.down_blocks.2.resnets.1.conv2.bias', 'encoder.down_blocks.2.downsamplers.0.conv.weight', 'encoder.down_blocks.2.downsamplers.0.conv.bias', 'encoder.down_blocks.3.resnets.0.norm1.weight', 'encoder.down_blocks.3.resnets.0.norm1.bias', 'encoder.down_blocks.3.resnets.0.conv1.weight', 'encoder.down_blocks.3.resnets.0.conv1.bias', 'encoder.down_blocks.3.resnets.0.norm2.weight', 'encoder.down_blocks.3.resnets.0.norm2.bias', 'encoder.down_blocks.3.resnets.0.conv2.weight', 'encoder.down_blocks.3.resnets.0.conv2.bias', 'encoder.down_blocks.3.resnets.1.norm1.weight', 'encoder.down_blocks.3.resnets.1.norm1.bias', 'encoder.down_blocks.3.resnets.1.conv1.weight', 'encoder.down_blocks.3.resnets.1.conv1.bias', 'encoder.down_blocks.3.resnets.1.norm2.weight', 'encoder.down_blocks.3.resnets.1.norm2.bias', 'encoder.down_blocks.3.resnets.1.conv2.weight', 'encoder.down_blocks.3.resnets.1.conv2.bias', 'encoder.mid_block.attentions.0.group_norm.weight', 'encoder.mid_block.attentions.0.group_norm.bias', 'encoder.mid_block.attentions.0.to_q.weight', 'encoder.mid_block.attentions.0.to_q.bias', 'encoder.mid_block.attentions.0.to_k.weight', 'encoder.mid_block.attentions.0.to_k.bias', 'encoder.mid_block.attentions.0.to_v.weight', 'encoder.mid_block.attentions.0.to_v.bias', 'encoder.mid_block.attentions.0.to_out.0.weight', 'encoder.mid_block.attentions.0.to_out.0.bias', 'encoder.mid_block.resnets.0.norm1.weight', 'encoder.mid_block.resnets.0.norm1.bias', 'encoder.mid_block.resnets.0.conv1.weight', 'encoder.mid_block.resnets.0.conv1.bias', 'encoder.mid_block.resnets.0.norm2.weight', 'encoder.mid_block.resnets.0.norm2.bias', 'encoder.mid_block.resnets.0.conv2.weight', 'encoder.mid_block.resnets.0.conv2.bias', 'encoder.mid_block.resnets.1.norm1.weight', 'encoder.mid_block.resnets.1.norm1.bias', 'encoder.mid_block.resnets.1.conv1.weight', 'encoder.mid_block.resnets.1.conv1.bias', 'encoder.mid_block.resnets.1.norm2.weight', 'encoder.mid_block.resnets.1.norm2.bias', 'encoder.mid_block.resnets.1.conv2.weight', 'encoder.mid_block.resnets.1.conv2.bias', 'encoder.conv_norm_out.weight', 'encoder.conv_norm_out.bias', 'encoder.conv_out.weight', 'encoder.conv_out.bias', 'decoder.up_blocks.0.resnets.0.norm1.weight', 'decoder.up_blocks.0.resnets.0.norm1.bias', 'decoder.up_blocks.0.resnets.0.conv1.weight', 'decoder.up_blocks.0.resnets.0.conv1.bias', 'decoder.up_blocks.0.resnets.0.norm2.weight', 'decoder.up_blocks.0.resnets.0.norm2.bias', 'decoder.up_blocks.0.resnets.0.conv2.weight', 'decoder.up_blocks.0.resnets.0.conv2.bias', 'decoder.up_blocks.0.resnets.1.norm1.weight', 'decoder.up_blocks.0.resnets.1.norm1.bias', 'decoder.up_blocks.0.resnets.1.conv1.weight', 'decoder.up_blocks.0.resnets.1.conv1.bias', 'decoder.up_blocks.0.resnets.1.norm2.weight', 'decoder.up_blocks.0.resnets.1.norm2.bias', 'decoder.up_blocks.0.resnets.1.conv2.weight', 'decoder.up_blocks.0.resnets.1.conv2.bias', 'decoder.up_blocks.0.resnets.2.norm1.weight', 'decoder.up_blocks.0.resnets.2.norm1.bias', 'decoder.up_blocks.0.resnets.2.conv1.weight', 'decoder.up_blocks.0.resnets.2.conv1.bias', 'decoder.up_blocks.0.resnets.2.norm2.weight', 'decoder.up_blocks.0.resnets.2.norm2.bias', 'decoder.up_blocks.0.resnets.2.conv2.weight', 'decoder.up_blocks.0.resnets.2.conv2.bias', 'decoder.up_blocks.0.upsamplers.0.conv.weight', 'decoder.up_blocks.0.upsamplers.0.conv.bias', 'decoder.up_blocks.1.resnets.0.norm1.weight', 'decoder.up_blocks.1.resnets.0.norm1.bias', 'decoder.up_blocks.1.resnets.0.conv1.weight', 'decoder.up_blocks.1.resnets.0.conv1.bias', 'decoder.up_blocks.1.resnets.0.norm2.weight', 'decoder.up_blocks.1.resnets.0.norm2.bias', 'decoder.up_blocks.1.resnets.0.conv2.weight', 'decoder.up_blocks.1.resnets.0.conv2.bias', 'decoder.up_blocks.1.resnets.1.norm1.weight', 'decoder.up_blocks.1.resnets.1.norm1.bias', 'decoder.up_blocks.1.resnets.1.conv1.weight', 'decoder.up_blocks.1.resnets.1.conv1.bias', 'decoder.up_blocks.1.resnets.1.norm2.weight', 'decoder.up_blocks.1.resnets.1.norm2.bias', 'decoder.up_blocks.1.resnets.1.conv2.weight', 'decoder.up_blocks.1.resnets.1.conv2.bias', 'decoder.up_blocks.1.resnets.2.norm1.weight', 'decoder.up_blocks.1.resnets.2.norm1.bias', 'decoder.up_blocks.1.resnets.2.conv1.weight', 'decoder.up_blocks.1.resnets.2.conv1.bias', 'decoder.up_blocks.1.resnets.2.norm2.weight', 'decoder.up_blocks.1.resnets.2.norm2.bias', 'decoder.up_blocks.1.resnets.2.conv2.weight', 'decoder.up_blocks.1.resnets.2.conv2.bias', 'decoder.up_blocks.1.upsamplers.0.conv.weight', 'decoder.up_blocks.1.upsamplers.0.conv.bias', 'decoder.up_blocks.2.resnets.0.norm1.weight', 'decoder.up_blocks.2.resnets.0.norm1.bias', 'decoder.up_blocks.2.resnets.0.conv1.weight', 'decoder.up_blocks.2.resnets.0.conv1.bias', 'decoder.up_blocks.2.resnets.0.norm2.weight', 'decoder.up_blocks.2.resnets.0.norm2.bias', 'decoder.up_blocks.2.resnets.0.conv2.weight', 'decoder.up_blocks.2.resnets.0.conv2.bias', 'decoder.up_blocks.2.resnets.0.conv_shortcut.weight', 'decoder.up_blocks.2.resnets.0.conv_shortcut.bias', 'decoder.up_blocks.2.resnets.1.norm1.weight', 'decoder.up_blocks.2.resnets.1.norm1.bias', 'decoder.up_blocks.2.resnets.1.conv1.weight', 'decoder.up_blocks.2.resnets.1.conv1.bias', 'decoder.up_blocks.2.resnets.1.norm2.weight', 'decoder.up_blocks.2.resnets.1.norm2.bias', 'decoder.up_blocks.2.resnets.1.conv2.weight', 'decoder.up_blocks.2.resnets.1.conv2.bias', 'decoder.up_blocks.2.resnets.2.norm1.weight', 'decoder.up_blocks.2.resnets.2.norm1.bias', 'decoder.up_blocks.2.resnets.2.conv1.weight', 'decoder.up_blocks.2.resnets.2.conv1.bias', 'decoder.up_blocks.2.resnets.2.norm2.weight', 'decoder.up_blocks.2.resnets.2.norm2.bias', 'decoder.up_blocks.2.resnets.2.conv2.weight', 'decoder.up_blocks.2.resnets.2.conv2.bias', 'decoder.up_blocks.2.upsamplers.0.conv.weight', 'decoder.up_blocks.2.upsamplers.0.conv.bias', 'decoder.up_blocks.3.resnets.0.norm1.weight', 'decoder.up_blocks.3.resnets.0.norm1.bias', 'decoder.up_blocks.3.resnets.0.conv1.weight', 'decoder.up_blocks.3.resnets.0.conv1.bias', 'decoder.up_blocks.3.resnets.0.norm2.weight', 'decoder.up_blocks.3.resnets.0.norm2.bias', 'decoder.up_blocks.3.resnets.0.conv2.weight', 'decoder.up_blocks.3.resnets.0.conv2.bias', 'decoder.up_blocks.3.resnets.0.conv_shortcut.weight', 'decoder.up_blocks.3.resnets.0.conv_shortcut.bias', 'decoder.up_blocks.3.resnets.1.norm1.weight', 'decoder.up_blocks.3.resnets.1.norm1.bias', 'decoder.up_blocks.3.resnets.1.conv1.weight', 'decoder.up_blocks.3.resnets.1.conv1.bias', 'decoder.up_blocks.3.resnets.1.norm2.weight', 'decoder.up_blocks.3.resnets.1.norm2.bias', 'decoder.up_blocks.3.resnets.1.conv2.weight', 'decoder.up_blocks.3.resnets.1.conv2.bias', 'decoder.up_blocks.3.resnets.2.norm1.weight', 'decoder.up_blocks.3.resnets.2.norm1.bias', 'decoder.up_blocks.3.resnets.2.conv1.weight', 'decoder.up_blocks.3.resnets.2.conv1.bias', 'decoder.up_blocks.3.resnets.2.norm2.weight', 'decoder.up_blocks.3.resnets.2.norm2.bias', 'decoder.up_blocks.3.resnets.2.conv2.weight', 'decoder.up_blocks.3.resnets.2.conv2.bias', 'decoder.mid_block.attentions.0.group_norm.weight', 'decoder.mid_block.attentions.0.group_norm.bias', 'decoder.mid_block.attentions.0.to_q.weight', 'decoder.mid_block.attentions.0.to_q.bias', 'decoder.mid_block.attentions.0.to_k.weight', 'decoder.mid_block.attentions.0.to_k.bias', 'decoder.mid_block.attentions.0.to_v.weight', 'decoder.mid_block.attentions.0.to_v.bias', 'decoder.mid_block.attentions.0.to_out.0.weight', 'decoder.mid_block.attentions.0.to_out.0.bias', 'decoder.mid_block.resnets.0.norm1.weight', 'decoder.mid_block.resnets.0.norm1.bias', 'decoder.mid_block.resnets.0.conv1.weight', 'decoder.mid_block.resnets.0.conv1.bias', 'decoder.mid_block.resnets.0.norm2.weight', 'decoder.mid_block.resnets.0.norm2.bias', 'decoder.mid_block.resnets.0.conv2.weight', 'decoder.mid_block.resnets.0.conv2.bias', 'decoder.mid_block.resnets.1.norm1.weight', 'decoder.mid_block.resnets.1.norm1.bias', 'decoder.mid_block.resnets.1.conv1.weight', 'decoder.mid_block.resnets.1.conv1.bias', 'decoder.mid_block.resnets.1.norm2.weight', 'decoder.mid_block.resnets.1.norm2.bias', 'decoder.mid_block.resnets.1.conv2.weight', 'decoder.mid_block.resnets.1.conv2.bias', 'decoder.conv_norm_out.weight', 'decoder.conv_norm_out.bias', 'quant_conv.weight', 'quant_conv.bias'], unexpected_keys=['decoder.mid.block_1.norm1.weight', 'decoder.mid.block_1.norm1.bias', 'decoder.mid.block_1.conv1.weight', 'decoder.mid.block_1.conv1.bias', 'decoder.mid.block_1.norm2.weight', 'decoder.mid.block_1.norm2.bias', 'decoder.mid.block_1.conv2.weight', 'decoder.mid.block_1.conv2.bias', 'decoder.mid.attn_1.norm.weight', 'decoder.mid.attn_1.norm.bias', 'decoder.mid.attn_1.q.weight', 'decoder.mid.attn_1.q.bias', 'decoder.mid.attn_1.k.weight', 'decoder.mid.attn_1.k.bias', 'decoder.mid.attn_1.v.weight', 'decoder.mid.attn_1.v.bias', 'decoder.mid.attn_1.proj_out.weight', 'decoder.mid.attn_1.proj_out.bias', 'decoder.mid.block_2.norm1.weight', 'decoder.mid.block_2.norm1.bias', 'decoder.mid.block_2.conv1.weight', 'decoder.mid.block_2.conv1.bias', 'decoder.mid.block_2.norm2.weight', 'decoder.mid.block_2.norm2.bias', 'decoder.mid.block_2.conv2.weight', 'decoder.mid.block_2.conv2.bias', 'decoder.up.0.block.0.norm1.weight', 'decoder.up.0.block.0.norm1.bias', 'decoder.up.0.block.0.conv1.weight', 'decoder.up.0.block.0.conv1.bias', 'decoder.up.0.block.0.norm2.weight', 'decoder.up.0.block.0.norm2.bias', 'decoder.up.0.block.0.conv2.weight', 'decoder.up.0.block.0.conv2.bias', 'decoder.up.0.block.0.nin_shortcut.weight', 'decoder.up.0.block.0.nin_shortcut.bias', 'decoder.up.0.block.1.norm1.weight', 'decoder.up.0.block.1.norm1.bias', 'decoder.up.0.block.1.conv1.weight', 'decoder.up.0.block.1.conv1.bias', 'decoder.up.0.block.1.norm2.weight', 'decoder.up.0.block.1.norm2.bias', 'decoder.up.0.block.1.conv2.weight', 'decoder.up.0.block.1.conv2.bias', 'decoder.up.0.block.2.norm1.weight', 'decoder.up.0.block.2.norm1.bias', 'decoder.up.0.block.2.conv1.weight', 'decoder.up.0.block.2.conv1.bias', 'decoder.up.0.block.2.norm2.weight', 'decoder.up.0.block.2.norm2.bias', 'decoder.up.0.block.2.conv2.weight', 'decoder.up.0.block.2.conv2.bias', 'decoder.up.1.block.0.norm1.weight', 'decoder.up.1.block.0.norm1.bias', 'decoder.up.1.block.0.conv1.weight', 'decoder.up.1.block.0.conv1.bias', 'decoder.up.1.block.0.norm2.weight', 'decoder.up.1.block.0.norm2.bias', 'decoder.up.1.block.0.conv2.weight', 'decoder.up.1.block.0.conv2.bias', 'decoder.up.1.block.0.nin_shortcut.weight', 'decoder.up.1.block.0.nin_shortcut.bias', 'decoder.up.1.block.1.norm1.weight', 'decoder.up.1.block.1.norm1.bias', 'decoder.up.1.block.1.conv1.weight', 'decoder.up.1.block.1.conv1.bias', 'decoder.up.1.block.1.norm2.weight', 'decoder.up.1.block.1.norm2.bias', 'decoder.up.1.block.1.conv2.weight', 'decoder.up.1.block.1.conv2.bias', 'decoder.up.1.block.2.norm1.weight', 'decoder.up.1.block.2.norm1.bias', 'decoder.up.1.block.2.conv1.weight', 'decoder.up.1.block.2.conv1.bias', 'decoder.up.1.block.2.norm2.weight', 'decoder.up.1.block.2.norm2.bias', 'decoder.up.1.block.2.conv2.weight', 'decoder.up.1.block.2.conv2.bias', 'decoder.up.1.upsample.conv.weight', 'decoder.up.1.upsample.conv.bias', 'decoder.up.2.block.0.norm1.weight', 'decoder.up.2.block.0.norm1.bias', 'decoder.up.2.block.0.conv1.weight', 'decoder.up.2.block.0.conv1.bias', 'decoder.up.2.block.0.norm2.weight', 'decoder.up.2.block.0.norm2.bias', 'decoder.up.2.block.0.conv2.weight', 'decoder.up.2.block.0.conv2.bias', 'decoder.up.2.block.1.norm1.weight', 'decoder.up.2.block.1.norm1.bias', 'decoder.up.2.block.1.conv1.weight', 'decoder.up.2.block.1.conv1.bias', 'decoder.up.2.block.1.norm2.weight', 'decoder.up.2.block.1.norm2.bias', 'decoder.up.2.block.1.conv2.weight', 'decoder.up.2.block.1.conv2.bias', 'decoder.up.2.block.2.norm1.weight', 'decoder.up.2.block.2.norm1.bias', 'decoder.up.2.block.2.conv1.weight', 'decoder.up.2.block.2.conv1.bias', 'decoder.up.2.block.2.norm2.weight', 'decoder.up.2.block.2.norm2.bias', 'decoder.up.2.block.2.conv2.weight', 'decoder.up.2.block.2.conv2.bias', 'decoder.up.2.upsample.conv.weight', 'decoder.up.2.upsample.conv.bias', 'decoder.up.3.block.0.norm1.weight', 'decoder.up.3.block.0.norm1.bias', 'decoder.up.3.block.0.conv1.weight', 'decoder.up.3.block.0.conv1.bias', 'decoder.up.3.block.0.norm2.weight', 'decoder.up.3.block.0.norm2.bias', 'decoder.up.3.block.0.conv2.weight', 'decoder.up.3.block.0.conv2.bias', 'decoder.up.3.block.1.norm1.weight', 'decoder.up.3.block.1.norm1.bias', 'decoder.up.3.block.1.conv1.weight', 'decoder.up.3.block.1.conv1.bias', 'decoder.up.3.block.1.norm2.weight', 'decoder.up.3.block.1.norm2.bias', 'decoder.up.3.block.1.conv2.weight', 'decoder.up.3.block.1.conv2.bias', 'decoder.up.3.block.2.norm1.weight', 'decoder.up.3.block.2.norm1.bias', 'decoder.up.3.block.2.conv1.weight', 'decoder.up.3.block.2.conv1.bias', 'decoder.up.3.block.2.norm2.weight', 'decoder.up.3.block.2.norm2.bias', 'decoder.up.3.block.2.conv2.weight', 'decoder.up.3.block.2.conv2.bias', 'decoder.up.3.upsample.conv.weight', 'decoder.up.3.upsample.conv.bias', 'decoder.norm_out.weight', 'decoder.norm_out.bias'])
the keys of decoder is incompatible as you can see and here is my code

`from diffusers.models import AutoencoderKL
from diffusers import DiffusionPipeline
import torch

model = "stable-diffusion-v1-4"

pipe = DiffusionPipeline.from_pretrained(model)

state_dict = torch.load("sd/sd2_decoder.pth")
msg = pipe.vae.load_state_dict(state_dict, strict=False)
print(f"loaded LDM decoder state_dict with message\n{msg}")
print("you should check that the decoder keys are correctly matched")

device = torch.device('cuda')
pipe.to(device)
img = pipe("the cat drinks milk.").images[0]
img.save('output/image.png')`

**Comment by holdrain** [comment]
there are only incompatible encoder keys when I use this code, but it seems like I get different watermark bits after extracting from the watermarked image 
![image](https://github.com/facebookresearch/stable_signature/assets/61930562/54c9dca9-7010-4b4e-b509-6d9fd8b18467)

**Comment by pierrefdz** [comment]
Ok, thanks for your answer. The issue seems to come from the diffuser/ transformers libraries.
I reverted the main branch to a previous commit that should work and that uses the stabilityai/stablediffusion repository instead.

In your code, the `pipe.vae.first_stage_model = ldm_aef` does not do anything. I tried to replace it with `= 'banana' ` and it stills generate the image.
A loophole I found is to do:
`pipe.vae.decode = (lambda x,  *args, **kwargs: ldm_aef.decode(x).unsqueeze(0))` instead, which should be working (transformers==4.25.1, diffusers==0.25.1). Could you tell me if it works for you?

I will try to look further into it in the following weeks (I don't have much time at the moment, sorry for that!).

**Comment by pierrefdz** [comment]
(I updated the README.md with a new code for the generate.)

**Comment by holdrain** [comment]
> (I updated the README.md with a new code for the generate.)

The new generate script does work, the embedding and extraction of the watermark is fine so far, thanks for the prompt reply!!!

**Comment by pierrefdz** [comment]
Closing since no more activity, don't hesitate to re-open
