### ISSUE TITLE
Please provide the subset of COCO dataset that you have used

### ISSUE THREAD

**Issue by neuralnaresh** [facebookresearch/stable_signature#23]
Dear Authors,

I am trying to reproduce the results mentioned in the Stable signature paper and I request you to kindly provide the subset of the coco dataset that you have used.

Hoping to hear from you soon.

Best Regards.

**Comment by pierrefdz** [comment]
Hi, we use the 2014 splits:
- for the training, we use the train subset
- for evaluation, we use the validation subset

Don't hesitate if you have further questions

**Comment by Vizzana** [comment]
You used the all images in COCO2014 training and validation dataset  for   training the  extractor in stable signature, right?

**Comment by pierrefdz** [comment]
Hi!
Yes, we used the whole dataset for training, the validation dataset is only used for FID (since the extraction is done on images generated from COCO prompts)
