### ISSUE TITLE
About Lamb Optimizer

### ISSUE THREAD

**Issue by Georgefwt** [facebookresearch/stable_signature#3]
Hello, I noticed that you used the Lamb optimizer when training "hidden". However, there's no implementation of it in the code, and Lamb isn't a built-in optimizer in pytorch-2.0. How can I use Lamb? Or if I were to use another optimizer, could you provide default parameters?

**Comment by pierrefdz** [comment]
Hi George,

The lamb optimizer should be available in the timm library (see https://github.com/huggingface/pytorch-image-models/blob/main/timm/optim/optim_factory.py).
The build_optimizer here https://github.com/facebookresearch/stable_signature/blob/main/hidden/utils.py#L175C13-L175C13 should build it automatically.

**Comment by Georgefwt** [comment]
I see, I forgot to install timm. sorry for the inconvenience.😂
