### ISSUE TITLE
Question about lpips

### ISSUE THREAD

**Issue by chbw818** [facebookresearch/stable_signature#9]
First of all, great work! But I'm a little confused about how to compute lpips.When I ran run_evals.py,I found that the way to compute lpips is not defined in the function [get_img_metric](https://github.com/facebookresearch/stable_signature/blob/341f8224500bf9aeb8c10af6d4aa06031e8eaf8c/run_evals.py#L44).So i wonder how to compute it.Looking forward to your reply!

**Comment by pierrefdz** [comment]
Hi, yes this is an error on the code. I removed the lpips logging from the run_eval.py. If you want you to add it, you can `pip install lpips` (see here: https://pypi.org/project/lpips/).

**Comment by chbw818** [comment]
Thank you for your rapid reply!I have searched on the Internet on how to compute the lpips before opening this issue,but none of their methods worked.I have successfully solved the problem using your method.Thanks!
